### ISSUE TITLE
Please make it more clear how to inject.

### ISSUE THREAD

**Issue by 987212455633179767** [Gh0stD14l3r/GhostWatchers-Internal-Hack#1]
what injector should we use exactly. My monosharpinjector doesent show any processes in the dropdown

**Comment by Gh0stD14l3r** [comment]
You can use any mono injector. Im using MonoSharpInjector and it works fine. Make sure your mono sharp injector files are still there as antivirus will delete them. Monosharp injector comes with a dll file and smi_gui.exe if you do not have the files it will not detect the window. If you have antivirus on its most likely blocking it from working.

Refer to the MonoSharpInjector's original post for more info.
https://www.unknowncheats.me/forum/unity/408878-sharpmonoinjector-fixed-updated.html

If you are unable to get MonoSharp working try Xenos, MInjector.

**Comment by Gh0stD14l3r** [comment]
Providing a picture to show that SharpMono Injector works. Also forgot to mention you need to run it as admin

![image](https://user-images.githubusercontent.com/38970826/184063459-c03ad29c-fbb8-4582-82e2-bcedcc1f7394.png)
