### ISSUE TITLE
Update sources

### ISSUE THREAD

**Issue by J0hannex** [Gh0stD14l3r/GhostWatchers-Internal-Hack#2]
Hello, will you update the sources for the new version, where there is a ghost spawner and a trolling menu?

**Comment by Gh0stD14l3r** [comment]
Yes most likely once I’ve done another large update. Unknowncheats.me will have the most updated version as a dll and the source will be a step behind

**Comment by J0hannex** [comment]
I can offer my cheat engine table, maybe some functions from it will be useful (if not already released by you). For example, invincible for all, prevent the game from ending if no alive players, make the player invisible to the ghost, prohibit throwing tools out of hand, make the ghost full weak enable/disable and other little things. But some functions in bad hands can ruin the game for people and it is better to apply them in the private version. I can't detour opcodes in C# mono like a C++.

**Comment by Gh0stD14l3r** [comment]
thanks for the input, I can add those features directly from managed code, I was quite selective with what and how i added extra features as i dont really want the game completely ruined for others. The Spawn system can easily ruin a game for people but the reason it was added was to provide an extra level of hardness for players. 

Some things i might add for in future is having dead players visible to each other and a little bit more interaction. In a private build for myself i can attach the ghost to dead players so essentially they play as the ghost. But limitations will be added aswell to prevent griefing.

**Comment by J0hannex** [comment]
I have added a table to my gw repository. I don't know how to implement some features without changing the original game code. If I turn on the invisibility, then I can control the ghost without harm to myself. I can try to make myself invisible to others. I now tried to make a name spoofer, but it didn’t work out, maybe I used the wrong class. If later there will be a private version of your cheat, you can conveniently implement key activation with binding to HWID via Keyauth.

By the way, in the Donteco.PlayerPersistentData class, you can call the SetDollars() method to get even amounts of money.

**Comment by Gh0stD14l3r** [comment]
Yes, I use that in the released version on UnknownCheats.me I specifically use the player wallet as theres a bug you can actually give other people money. If you want to get into managed code game hacking you can check out unknowncheats. There are threads that will show you C# tutorials etc

**Comment by J0hannex** [comment]
It’s more easy for me to offer ideas and developments for an existing cheat than to make my own). Now i have improved your FLY cheat and now it's a noclip, with ignoring world objects and hanging in the air. But again, I had to disable game movement function through detouring game code. Need code for noclip ?

**Comment by Gh0stD14l3r** [comment]
you can add no clip by increasing the value for the forward movement. Ive kept it low so you can still semi use it as a speedhack and small no clipping on doors or thin objects.

**Comment by J0hannex** [comment]
Yes, it works like a teleport forward at 0.3f, but I use smooth with CharacterController.radius = float.PositiveInfinity.
